import { Ele } from "../../Class/EleClass";
import {
  NewContent,
  NewContentType2,
  NewScriptContent,
  NewScriptContentType2,
  NewTextContent,
  NewTextContentType2,
  NewConditionContent,
  NewConditionContentType2,
  NewQuestionContent,
  NewQuestionContentType2,
  NewBlockContent,
  NewBlockContentType2,
  NewMarkContent,
  NewMarkContentType2,
  NewExecutionContent,
  NewExecutionContentType2,
  NewLoopContent,
  NewLoopContentType2,
  NewQuotaContent,
  NewQuotaContentType2,
} from "./Content";

import {
  NewItem,
  NewItemType2,
  NewHtmlItem,
  NewHtmlItemType2,
  NewScriptItem,
  NewScriptItemType2,
  NewOptionItem,
  NewTextScriptItem,
  NewTextScriptItemType2,
  NewExcutionScriptItem,
  NewExcutionScriptItemType2,
  NewConditionScriptItem,
  NewConditionScriptItemType2,
  NewBuiltinConditionScriptItem,
  NewBuiltinConditionScriptItemType2,
  NewBuiltinExcutionScriptItem,
  NewBuiltinExcutionScriptItemType2,
  NewBuiltinTextScriptItem,
  NewBuiltinTextScriptItemType2,
} from "./Item";

import {
  NewList,
  NewListType2,
  NewConditionList,
  NewConditionListType2,
  NewQuestionnaireList,
  NewQuestionnaireListType2,
  NewTextList,
  NewTextListType2,
  NewOptionList,
  NewOptionListType2,
} from "./List";

import {
  NewNode,
  NewNodeType2,
  NewQuestionNode,
  NewQuestionNodeType2,
  NewBlockNode,
  NewBlockNodeType2,
  NewExecutionNode,
  NewExecutionNodeType2,
  NewMarkNode,
  NewMarkNodeType2,
  NewLoopNode,
  NewLoopNodeType2,
  NewQuotaNode,
  NewQuotaNodeType2,
} from "./Node";
const NewEle = new Ele("Eleid", "Ele", null, null);
const NewEleType2 = new Ele("Eleid", "Ele", {}, {});

export {
  NewContent,
  NewContentType2,
  NewScriptContent,
  NewScriptContentType2,
  NewTextContent,
  NewTextContentType2,
  NewConditionContent,
  NewConditionContentType2,
  NewQuestionContent,
  NewQuestionContentType2,
  NewBlockContent,
  NewBlockContentType2,
  NewMarkContent,
  NewMarkContentType2,
  NewExecutionContent,
  NewExecutionContentType2,
  NewLoopContent,
  NewLoopContentType2,
  NewQuotaContent,
  NewQuotaContentType2,
  NewItem,
  NewItemType2,
  NewHtmlItem,
  NewHtmlItemType2,
  NewScriptItem,
  NewScriptItemType2,
  NewOptionItem,
  NewTextScriptItem,
  NewTextScriptItemType2,
  NewExcutionScriptItem,
  NewExcutionScriptItemType2,
  NewConditionScriptItem,
  NewConditionScriptItemType2,
  NewBuiltinConditionScriptItem,
  NewBuiltinConditionScriptItemType2,
  NewBuiltinExcutionScriptItem,
  NewBuiltinExcutionScriptItemType2,
  NewBuiltinTextScriptItem,
  NewBuiltinTextScriptItemType2,
  NewList,
  NewListType2,
  NewConditionList,
  NewConditionListType2,
  NewQuestionnaireList,
  NewQuestionnaireListType2,
  NewTextList,
  NewTextListType2,
  NewOptionList,
  NewOptionListType2,
  NewNode,
  NewNodeType2,
  NewQuestionNode,
  NewQuestionNodeType2,
  NewBlockNode,
  NewBlockNodeType2,
  NewExecutionNode,
  NewExecutionNodeType2,
  NewMarkNode,
  NewMarkNodeType2,
  NewLoopNode,
  NewLoopNodeType2,
  NewQuotaNode,
  NewQuotaNodeType2,
  NewEle,
  NewEleType2,
};
